// Fallback addresses for development (Base Sepolia)
const FALLBACK_ADDRESSES = {
  YRT_FACTORY: '0x55D6DA78bf5FFc9d32D54dCB259E83aF466A2C73',
  AUTO_DISTRIBUTOR: '0x42C8c58dd12890AF6C0A23C222375f9D0CBb8FA2',
  DEX_ROUTER: '0x5b93C4A81534C170cfdC228b3dc0047694AdF8a5',
  DEX_FACTORY: '0xeDbe28c77C9f4509d50FA2C4CDA247fd96A7A69b',
  SECONDARY_MARKET: '0x9ED36dd97796bA008677474b8920eba1649e1a91',
  USDC: '0x1771B7f93FD4d06a6c0402F76D8cE64B95fcC906',
  IDRX: '0xD0Eae13E9bC49Ed4D3385832f9a07bAcD8C27532',
} as const;
export const CONTRACTS = {
  // YRT Token Factory (v1.0 - Slug System & Hybrid Roles)
  YRT_FACTORY: (process.env.NEXT_PUBLIC_YRT_FACTORY_ADDRESS || FALLBACK_ADDRESSES.YRT_FACTORY) as `0x${string}`,
  AUTO_DISTRIBUTOR: (process.env.NEXT_PUBLIC_AUTO_DISTRIBUTOR_ADDRESS || FALLBACK_ADDRESSES.AUTO_DISTRIBUTOR) as `0x${string}`,

  // Trading Markets (v1.0 - Property Owner Features)
  // DEX Router is the interface to access DEX Factory and all pools
  DEX_ROUTER: (process.env.NEXT_PUBLIC_DEX_ROUTER_ADDRESS || FALLBACK_ADDRESSES.DEX_ROUTER) as `0x${string}`,
  DEX_FACTORY: (process.env.NEXT_PUBLIC_DEX_FACTORY_ADDRESS || FALLBACK_ADDRESSES.DEX_FACTORY) as `0x${string}`,
  SECONDARY_MARKET: (process.env.NEXT_PUBLIC_SECONDARY_MARKET_ADDRESS || FALLBACK_ADDRESSES.SECONDARY_MARKET) as `0x${string}`,

  // Mock Stablecoins (Testnet - 18 decimals)
  USDC: (process.env.NEXT_PUBLIC_USDC_ADDRESS || FALLBACK_ADDRESSES.USDC) as `0x${string}`,
  IDRX: (process.env.NEXT_PUBLIC_IDRX_ADDRESS || FALLBACK_ADDRESSES.IDRX) as `0x${string}`,
} as const

// DEX Factory discovery through DEX Router
export const DEX_ROUTER = CONTRACTS.DEX_ROUTER;

// Legacy support for backward compatibility
export const LEGACY_CONTRACTS = {
  FACTORY: CONTRACTS.YRT_FACTORY,
  DISTRIBUTOR: CONTRACTS.AUTO_DISTRIBUTOR,
  DEX: CONTRACTS.DEX_ROUTER, // Legacy: This is actually DEX Router
} as const
